update features.md
vanus-labs/docs pull request #262
Opened 2023-02-17 15:03 UTC by bowen12001

### Related Issue

Solving Issue: #xxx

### PR Summary

### PR Type

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [ ] Update inappropriate or misunderstanding content
- [ ] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents
- [ ] Deal with GitHub action files and scripts
- [ ] Deal with chores

2023-02-17 15:43 UTC, wenfengwang requested changes

2023-02-17 15:43 UTC, wenfengwang commented on content/introduction/features.md
> +* The storage node is completely based on k8s design, multiple copies, and supports multi-level storage.
multi-level -> multi-tier

2023-02-17 15:43 UTC, wenfengwang commented on content/introduction/features.md
> +* Limited resource usage, each pod in the cluster can run with 0.1 core and 500M memory.
0.5 core is better

2023-02-17 15:43 UTC, wenfengwang commented on content/introduction/features.md
> +* There is an independent computing cluster that supports real-time computing of events, including filtering and conversion.
conversion -> Transformation

2023-02-17 15:44 UTC, wenfengwang requested changes

2023-02-17 15:44 UTC, wenfengwang commented on content/introduction/features.md
> +* Real push model.
model -> mode

2023-02-17 15:44 UTC, wenfengwang commented on content/introduction/features.md
> +* Seamlessly integrate cloud functions such as Aws lambda, Google Cloud Function, and Knative.
AWS Lambda

2023-02-18 02:44 UTC, bowen12001 commented on content/introduction/features.md
> +**Lightweight & K8s native:**
done

2023-02-18 02:44 UTC, bowen12001 commented on content/introduction/features.md
> +* There is an independent computing cluster that supports real-time computing of events, including filtering and conversion.
done

2023-02-18 02:44 UTC, bowen12001 commented on content/introduction/features.md
> +**Entirely elastic:**
done

2023-02-18 02:44 UTC, bowen12001 commented on content/introduction/features.md
> +* Real push model.
done

2023-02-18 02:44 UTC, bowen12001 commented on content/introduction/features.md
> +* Seamlessly integrate cloud functions such as Aws lambda, Google Cloud Function, and Knative.
done

2023-02-20 09:28 UTC, Michaelg22 commented on content/introduction/features.md
> +Vanus has a vast amount of features to help users achieve their goals. Let us share with you some of the key features Vanus has to offer.
```suggestion
Vanus offers an extensive range of features that help users accomplish their objectives. We'd like to highlight some of the key features that Vanus provides.
```

2023-02-20 09:33 UTC, Michaelg22 requested changes

2023-02-20 09:33 UTC, Michaelg22 commented on content/introduction/features.md
> +* Support for window-based event computing (come soon).
```suggestion
* Support for window-based event computing (coming soon).
```

2023-02-21 11:46 UTC, Michaelg22 approved these changes

2023-02-24 03:34 UTC, merged